<?php

namespace IMRIM\Bundle\LmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamAttemptsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamAttemptsRepository extends EntityRepository
{
}