<?php

namespace IMRIM\Bundle\LmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    /**
     * Find a specific user using his/her first name, last name or login
     * @param string $searchString
     * @return ArrayCollection() 
     */
    public function findByIdentity($searchString) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT u FROM IMRIMLmsBundle:User u WHERE UPPER(u.login) LIKE :searchString OR UPPER(u.firstName) LIKE :searchString OR UPPER(u.lastName) LIKE :searchString");
        $searchString = '%' . strtoupper($searchString) . '%';
        $query->setParameter('searchString', $searchString);
        return $query->getResult();
    }
}