<?php

namespace IMRIM\Bundle\LmsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use IMRIM\Bundle\LmsBundle\Entity\User;

/**
 * UserEnrolmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEnrolmentRepository extends EntityRepository
{
    /**
     * Find courses to which the user is enrolled
     * @param User $user
     * @return Doctrine\Common\Collections\Collection 
     */
    public function findUserCourses(User $user)
    {
        $query = $this->getEntityManager()
                ->createQuery('SELECT ue, c FROM IMRIMLmsBundle:UserEnrolment ue JOIN ue.course c WHERE ue.user= :user');
        $query->setParameter('user', $user);
        return $query->getResult();
    }
    
    public function findOneByUserAndCourse(User $user, Course $course)
    {
        $query = $this->getEntityManager()
                ->createQuery('SELECT ue FROM IMRIMLmsBundle:UserEnrolment ue WHERE ue.user= :user AND ue.course= :course');
        $query->setParameter('user', $user);
        $query->setParameter('course', $course);
        $result = $query->getResult();
        if(count($result) > 0)
        {
            return $result[0];  
        }
        return null;
    }
}